#!/usr/bin/env python3
import os

response_body = (
    "<!DOCTYPE html>\r\n"
    "<html lang='en'>\r\n"
    "<head>\r\n"
    "    <meta charset='UTF-8'>\r\n"
    "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\r\n"
    "    <title>Simple CGI Test</title>\r\n"
    "</head>\r\n"
    "<body>\r\n"
    "    <h2></h2>\r\n"
    "    <h1>CGI Script is Working!</h1>\r\n"
    "    <p>This is a simple HTML page generated by a Python CGI script.</p>\r\n"
    "</body>\r\n"
    "</html>\r\n"
)

# CGIでheadersとbodyのみ作成した場合はserver側でstatus lineを追加しなければならない -> nginxはそうなっている
# Content-Length headerをCGIで追加しなかった場合(例えばContent-Typeのみ持たせた場合など)、serverでContent-Lengthを追加しなければならない
# もしheader fieldを一つも持たないものをCGI ResposneとしてCGIが作成した場合、serverは502 Bad Gatewayを返す 
response = (
    "HTTP/1.1 200 OK\r\n"
    f"Content-Length: {len(response_body)}\r\n"
    "\r\n"
    f"{response_body}"
)

# ソケットを通じてレスポンスを送信
print(response)