#!/usr/bin/env python3

print("Content-Type: text/html")  # 必須のHTTPヘッダー
print()  # 空行でヘッダーと本文を分ける
print("""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Simple CGI Test</title>
</head>
<body>
    <h1>CGI Script is Working!</h1>
    <p>This is a simple HTML page generated by a Python CGI script.</p>
</body>
</html>
""")

