#!/usr/bin/env python3

from datetime import datetime, timezone, timedelta

# 日本標準時 (JST) のタイムゾーンを作成
JST = timezone(timedelta(hours=9))

# 現在の日本時間を取得
current_time = datetime.now(JST).strftime('%Y-%m-%d %H:%M:%S')

print("Content-Type: text/html")  # 必須のHTTPヘッダー
print()  # 空行でヘッダーと本文を分ける
print(f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Simple CGI Test</title>
</head>
<body>
    <h1>CGI Script is Working!</h1>
    <p>This is a simple HTML page generated by a Python CGI script.</p>
    <p>Current Time in Japan (JST): {current_time}</p>
</body>
</html>
""")

